matrix:
  include:
    - language: node_js
      node_js:
        - "9"
      dist: trusty
      sudo: required
      branches:
        only:
          - develop
      before_script:
        - cd igamt-hl7-client-v2
        - npm install
        - npm install -g @angular/cli
      script:
        - ng lint
        - ng build --prod --base-href https://github.com/usnistgov/hl7-igamt/

    - language: java
      jdk:
        - oraclejdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
      branches:
        only:
          - develop
      script:
        - mvn -Dmaven.test.skip=true install
