matrix:
  include:
    - language: node_js
      node_js:
        - "9"
      dist: trusty
      sudo: required
      branches:
        only:
          - develop
          - staging
      before_script:
        - cd igamt-hl7-client-v2
        - travis_wait npm install
        - travis_wait npm install -g @angular/cli
      script:
        - travis_wait ng lint
        - travis_wait ng build --prod --base-href https://github.com/usnistgov/hl7-igamt/
notifications:
  slack: igamt:AguUmFpxIC0okakY5LtQ3c22
