name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      back-end-directory: hl7-igamt
      front-end-directory: hl7-igamt/igamt-hl7-client-v2
      auth-project-directory: hl7-auth
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Checkout IGAMT
        uses: actions/checkout@v2
        with:
          path: hl7-igamt
        
      - name: Decrypt Secrets
        working-directory: ${{env.back-end-directory}}
        env:
          PK_ENCRYPTION_KEY: ${{ secrets.PK_ENCRYPTION_KEY }}
        run: gpg --quiet --batch --yes --passphrase=$PK_ENCRYPTION_KEY --decrypt --output unencryped_public_key.txt public_key.txt.gpg
      
     
        
        
